---

version: '2.1'

services:
  web:
    image: liberit/gridcoin
    container_name: gridcoin
    restart: always
    volumes:
      - $HOME/.GridcoinResearch:/root/.GridcoinResearch
      - /var/lib/boinc-client:/var/lib/boinc-client

networks:
  default:
    external:
      name: nginx-proxy_net
